# .github/workflows/deploy.yml
name: Validar, Construir e Implementar Bundle no Databricks

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      # Passo 1: Faz o checkout do código do repositório
      - name: Checkout código
        uses: actions/checkout@v4

      # Passo 2: Instala a CLI unificada do Databricks
      - name: Instalar Databricks CLI
        run: curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sudo sh
      
      # Passo 3: Valida, Constrói e Implementa o Bundle
      - name: Validar, Construir e Implementar o Bundle
        # Documentação:
        # A linha 'working-directory' é a chave da solução.
        # Ela instrui o GitHub Actions a executar todos os comandos deste step
        # DENTRO da pasta especificada. É como fazer um 'cd' antes de rodar os comandos.
        # Certifique-se de que 'etl_assets_bundles_dlt' é o nome exato da pasta
        # que contém seu arquivo databricks.yml.
        working-directory: ./etl_assets_bundles_dlt # <-- ESTA É A CORREÇÃO!
        run: |
          databricks bundle validate
          databricks bundle build
          databricks bundle deploy -t dev --auto-approve