from pyspark.sql.types import (StructType, StructField, IntegerType, StringType,
                               DateType, DoubleType, BooleanType, TimestampType)

# Definição do schema para a tabela final dev.raw.hoteis
# Inclui comentários detalhados (metadata) para cada coluna.

schema_raw_hoteis = StructType([
    # Colunas da Tabela de Origem (source_hoteis)
    StructField("hotel_id", IntegerType(), False, 
                metadata={"comment": "Chave primária única para cada hotel da rede."}),
    StructField("nome_hotel", StringType(), True, 
                metadata={"comment": "Nome comercial do hotel."}),
    StructField("endereco", StringType(), True, 
                metadata={"comment": "Endereço completo do hotel (Rua, número)."}),
    StructField("cidade", StringType(), True, 
                metadata={"comment": "Cidade onde o hotel está localizado."}),
    StructField("estado", StringType(), True, 
                metadata={"comment": "Estado (UF) onde o hotel está localizado."}),
    StructField("estrelas", IntegerType(), True, 
                metadata={"comment": "Classificação de estrelas do hotel (ex: 3, 4, 5)."}),
    StructField("numero_quartos", IntegerType(), True, 
                metadata={"comment": "Quantidade total de unidades (quartos) no hotel."}),
    StructField("comodidades", StringType(), True, 
                metadata={"comment": "Lista de comodidades principais (ex: 'Piscina, Spa')."}),
    StructField("telefone", StringType(), True, 
                metadata={"comment": "Número de telefone principal do hotel."}),
    StructField("email_contato", StringType(), True, 
                metadata={"comment": "Endereço de e-mail principal para contato."}),
    StructField("data_abertura", DateType(), True, 
                metadata={"comment": "Data de inauguração ou aquisição do hotel pela rede."}),
    StructField("horario_checkin", StringType(), True, 
                metadata={"comment": "Horário padrão de check-in (ex: '14:00')."}),
    StructField("horario_checkout", StringType(), True, 
                metadata={"comment": "Horário padrão de check-out (ex: '12:00')."}),
    StructField("categoria_hotel", StringType(), True, 
                metadata={"comment": "Classificação comercial (ex: 'Luxo', 'Business', 'Econômico')."}),
    StructField("tipo_hotel", StringType(), True, 
                metadata={"comment": "Tipo de localização ou vocação (ex: 'Praia', 'Urbano')."}),
    StructField("ano_fundacao", IntegerType(), True, 
                metadata={"comment": "Ano de construção original do edifício."}),
    StructField("capacidade_total", IntegerType(), True, 
                metadata={"comment": "Capacidade máxima estimada de hóspedes no hotel."}),
    StructField("possui_acessibilidade", BooleanType(), True, 
                metadata={"comment": "Indicador se o hotel possui infraestrutura de acessibilidade."}),
    StructField("certificacoes", StringType(), True, 
                metadata={"comment": "Lista de certificações do hotel (ex: 'ISO 9001', 'Green Key')."}),
    StructField("latitude", DoubleType(), True, 
                metadata={"comment": "Coordenada geográfica de latitude."}),
    StructField("longitude", DoubleType(), True, 
                metadata={"comment": "Coordenada geográfica de longitude."}),
    StructField("descricao_hotel", StringType(), True, 
                metadata={"comment": "Breve texto descritivo sobre o hotel."}),
    StructField("numero_funcionarios", IntegerType(), True, 
                metadata={"comment": "Número aproximado de funcionários."}),

    # Colunas de Auditoria (Controle)
    StructField("insert_date", TimestampType(), True, 
                metadata={"comment": "Data e hora em que o registro foi inserido pela primeira vez na camada Raw."}),
    StructField("update_date", TimestampType(), True, 
                metadata={"comment": "Data e hora da última atualização do registro na camada Raw."})
])